version: "3.0"

volumes:
  node-mongo-keys:
  node-mongo-data-0:
  node-mongo-data-1:
  node-mongo-data-2:
  node-mongo-data-3:

networks:
  profile-replica-set:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.5.0/24

services:
  node-mongo-keys:
    image: depop/openssl-bats
    volumes:
      - node-mongo-keys:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  # Primary
  node-mongo-primary:
    image: mongo:latest
    volumes:
      - node-mongo-keys:/opt/keyfile
      - node-mongo-data-0:/data/db
    env_file: ./mongod.env
    ports:
      - 27017:27017
    command: "mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet profile-replica-set"
    depends_on:
      - node-mongo-keys
    networks:
      profile-replica-set:

  # Worker 1
  tut12-mongo-worker-1:
    image: mongo:latest
    volumes:
      - node-mongo-keys:/opt/keyfile
      - node-mongo-data-1:/data/db
    env_file: ./mongod.env
    ports:
      - 27018:27017
    command: "mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet profile-replica-set"
    depends_on:
      - node-mongo-keys
    networks:
      profile-replica-set:

  # Worker 2
  tut12-mongo-worker-2:
    image: mongo:latest
    volumes:
      - node-mongo-keys:/opt/keyfile
      - node-mongo-data-2:/data/db
    env_file: ./mongod.env
    ports:
      - 27019:27017
    command: "mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet profile-replica-set"
    depends_on:
      - node-mongo-keys
    networks:
      profile-replica-set:

  # Worker 3
  tut12-mongo-worker-3:
    image: mongo:latest
    volumes:
      - node-mongo-keys:/opt/keyfile
      - node-mongo-data-3:/data/db
    env_file: ./mongod.env
    ports:
      - 27020:27017
    command: "mongod --auth --keyFile /opt/keyfile/mongodb-keyfile --replSet profile-replica-set"
    depends_on:
      - node-mongo-keys
    networks:
      profile-replica-set:
